# Generated by Django 5.0.2 on 2024-03-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=10, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('latitude_deg', models.FloatField()),
                ('longitude_deg', models.FloatField()),
                ('elevation_ft', models.IntegerField(blank=True, null=True)),
                ('continent', models.CharField(max_length=2)),
                ('iso_country', models.CharField(max_length=2)),
                ('iso_region', models.CharField(max_length=7)),
            ],
        ),
    ]
