# Generated by Django 5.0.2 on 2024-03-03 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ident', models.CharField(max_length=4, unique=True)),
                ('latitude_deg', models.FloatField()),
                ('longitude_deg', models.FloatField()),
                ('frequency', models.FloatField(blank=True, default=0, null=True)),
                ('type', models.CharField(max_length=3)),
                ('division', models.CharField(max_length=10)),
                ('vatsim_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
