# Generated by Django 5.0.2 on 2024-03-03 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_controller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='name',
        ),
    ]
