# Generated by Django 5.0.2 on 2024-03-04 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_controller_airport_alter_controller_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
