# Generated by Django 5.0.2 on 2024-03-04 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_controller_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controller',
            name='name',
        ),
    ]
