# Generated by Django 5.0.2 on 2024-03-04 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_controller_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='vatsim_id',
            field=models.IntegerField(),
        ),
    ]
