# Generated by Django 5.0.2 on 2024-03-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_controller_vatsim_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
