# Generated by Django 5.0.2 on 2024-03-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_controller_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=10)),
                ('latitude_deg', models.FloatField()),
                ('longitude_deg', models.FloatField()),
            ],
        ),
    ]
