# Generated by Django 5.0.2 on 2024-03-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_waypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='VATSIMFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vatsim_id', models.IntegerField()),
                ('callsign', models.CharField(max_length=10)),
                ('departure', models.CharField(max_length=4)),
                ('arrival', models.CharField(max_length=4)),
                ('aircraft', models.CharField(max_length=255)),
                ('cruise_speed', models.IntegerField()),
                ('altitude', models.IntegerField()),
                ('route', models.TextField()),
            ],
        ),
    ]
