# Generated by Django 5.0.2 on 2024-03-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_vatsimflight_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vatsimflight',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
