# Generated by Django 5.0.2 on 2024-03-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_alter_vatsimflight_departure_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vatsimflight',
            name='departure_time',
        ),
    ]
