# Generated by Django 5.0.2 on 2024-03-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_remove_vatsimflight_departure_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icao', models.CharField(max_length=4)),
            ],
        ),
    ]
