# Generated by Django 5.0.2 on 2024-03-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_airline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='icao',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
