# Generated by Django 5.0.2 on 2024-03-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_remove_controller_geoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='geoname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
