# Generated by Django 5.0.2 on 2024-03-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_controller_geoname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='division',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
