# Generated by Django 5.0.1 on 2024-02-23 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hours',
        ),
    ]
