# Generated by Django 5.0.2 on 2024-03-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='simbrief_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
