# Generated by Django 5.0.2 on 2024-02-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_flight_current_altitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='current_altitude',
            field=models.IntegerField(default=0),
        ),
    ]
