# Generated by Django 5.0.2 on 2024-02-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_flight_is_active_alter_flight_current_altitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
