# Generated by Django 5.0.2 on 2024-02-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_flight_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='landing_rate',
            field=models.IntegerField(default=0),
        ),
    ]
