# Generated by Django 5.0.1 on 2024-02-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_flight_landing_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
