# Generated by Django 5.0.1 on 2024-02-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_flight_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='target_altitude',
            field=models.IntegerField(default=0),
        ),
    ]
