# Generated by Django 5.0.1 on 2024-02-24 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_flight_target_altitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_time',
        ),
    ]
