# Generated by Django 5.0.2 on 2024-02-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_flight_flight_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='aircraft_ground_speed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft_heading',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft_latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft_longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='flight',
            name='aircraft_vertical_speed',
            field=models.IntegerField(default=0),
        ),
    ]
